---
name: Java CI (autogen)

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.372+7'
        distribution: 'temurin'
    - name: Run mvn install
      run: |
        ./mvnw -B install -DskipTests -Dmaven.javadoc.skip=true -Dair.check.skip-all=true

    - name: Run tests
      run: |
        ./mvnw test -B

    - name: Build with Maven
      run: ./mvnw clean install
